kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: test-sugiyama
spec:
  scaleTargetRef:
    # point the HPA at the sample application
    # you created above
    apiVersion: apps/v1
    kind: Deployment
    name: test-sugiyama
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      # use the metric that you used above: pods/memory_usage_bytes
      metric:
        name: memory_usage_bytes
      target:
        type: Value
        averageValue: 10485760 # 10M