# apiVersion: autoscaling/v2beta2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: test-sugiyama
#   namespace: buildkite
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: test-sugiyama
#   minReplicas: 1
#   maxReplicas: 3
#   metrics:
#     - type: External
#       external:
#         metric:
#           name: 
#         target:
#           type: Value
#           value: 60
#   behavior:
#     scaleDown:
#       stabilizationWindowSeconds: 60
#       policies:
#         - type: Percent
#           value: 25
#           periodSeconds: 300
#     scaleUp:
#       stabilizationWindowSeconds: 30
#       policies:
#         - type: Percent
#           value: 50
#           periodSeconds: 60

