kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: test-sugiyama
spec:
  scaleTargetRef:
    # point the HPA at the sample application
    # you created above
    apiVersion: apps/v1
    kind: Deployment
    name: test-sugiyama
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: External
    external:
      metric:
        name: my_external_metric
      target:
        type: Value
        value: "2"