kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: test-sugiyama
spec:
  scaleTargetRef:
    # point the HPA at the sample application
    # you created above
    apiVersion: apps/v1
    kind: Deployment
    name: test-sugiyama
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: my_custom_metric
      target:
        type: Value
        value: "1"